
economy: #Types: thepit, vault
  type: thepit
  starting_balance: 150
arena:
  random_gold_spawn:
    item: random_gold #Item id, in items.yml file
    amount: 5 # The amount of money players receive
    period: 100 # The time between each gold spawn
    all_locations: false # Spawning gold in all arenas gold_spawn locations
    allow_stack: false # Allows gold to be spawned multiple times in a specific location
    hologram:
      enabled: true
      text: "&6&lGOLD"
  on_join:
    held_item_slot: 0
    clear_inventory: true
    clear_effects: true
    health: 20
    food_level: 20
    saturation: 5
  force_join_arena:
    enabled: false
    arena: ThePit

lobby_location: {}
