
economy: #Types: thepit, vault
  type: thepit
  starting_balance: 150
arena:
  random_gold_spawn:
    item: random_gold #In items.yml
    amount: 5 # The amount of money players receive
    period: 800 # The time between each gold spawn
    all_locations: false # Should spawn gold in all arenas gold spawn locations?
  on_join:
    held_item_slot: 0
    clear_inventory: true
    clear_effects: true
    health: 20
    food_level: 20
    saturation: 5
  force_join_arena:
    enabled: false
    arena: ThePit
